### ISSUE TITLE
BitFlags larger than 8 bits breaks in python 3.13

### ISSUE THREAD

**Issue by yearski** [justengel/bitflags#2]
First off, thanks for this module. It was such a joy to discover your solution that fit my needs so perfectly. It's a very well thought out implementation.

Some of my code broke when I upgraded to python 3.13. I've been able to figure out that BitFlags are somehow getting limited to 1 byte/8 bits.

Here's a sample:
```
from bitflags import BitFlags
import sys

class MyFlags(BitFlags):
    options = {
        0:  'b00',
        1:  'b01',
        2:  'b02',
        3:  'b03',
        4:  'b04',
        5:  'b05',
        6:  'b06',
        7:  'b07',
        8:  'b08',
        9:  'b09',
        10: 'b10',
        11: 'b11',
        12: 'b12',
        13: 'b13',
        14: 'b14',
        15: 'b15'
    }
f = MyFlags(65535)

print(sys.version)
print(f.get_flags())
print(hasattr(f, 'b08'))
```
python 3.12:
```
3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)]
['b00', 'b01', 'b02', 'b03', 'b04', 'b05', 'b06', 'b07', 'b08', 'b09', 'b10', 'b11', 'b12', 'b13', 'b14', 'b15']
True
```
python 3.13:
```
3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
['b00', 'b01', 'b02', 'b03', 'b04', 'b05', 'b06', 'b07']
False
```

I've also tried explicitly adding `nbits = 16` and/or `nbytes = 2` but neither had an effect.

**Comment by justengel** [comment]
Thank you for bringing this to my attention. I guess in the metaclass `__new__` setting an alias to the predefined `bit_0, bit_1, ...` attributes caused an issue. I moved this to the metaclass `__init__` and it seemed to work. This fix is in version 1.2.0 along with several other changes for variable names.

See `bitflags/tests/test_gh_issue_2.py`
