### ISSUE TITLE
inconsistent capitalization "flags" vs attributes (minor/low)

### ISSUE THREAD

**Issue by yearski** [justengel/bitflags#3]
If I define flags with upper case characters, the "flags" match my option definition. However, the attributes are converted to lowercase. I'd prefer if the attributes also kept the same character case. Alternatively, the flag should also be converted to lower case so that it is at least consistent with the attribute.

Example:
```
class MyFlags(BitFlags):
    
    options = {
        0:  'flag0',
        1:  'FLAG1'
    }

f = MyFlags(3)

print(f.get_flags())
print(hasattr(f, 'FLAG1'))
print(hasattr(f, 'flag1'))
```
output:
```
['flag0', 'FLAG1']
False
True
```

**Comment by justengel** [comment]
I added a way to change variable names. You can use `case_type = "keep"` or make your own function `case_func = lambda name: name.replace(" ", "_").upper()`. This is available in version 1.2.0

See `bitflags/tests/test_gh_issue_3.py`
